### PR TITLE
Experimental update to IPropertyBag

### LINKED ISSUE #94: Support ITenantStore/ITenantProvider split
Corvus.Tenancy now separates read and write.

Consistent with the new property bag way of doing things, modify the tenancy API to update tenants via a PATCH, rather than requiring callers to download the tenant, make changes, then PUT the entire tenant back again.

### PR DESCRIPTION
**Pull request by idg10**
Resolves #94

### CODE REVIEW

**Comment by mwadams** [comment]
This feels like a case where there should be some "helper" methods for the Client SDK to give you some strongly typed `SetName`, `SetProperty<T>(string name, T! value)" and `DeleteProperty(string name)`, and the patch is hidden from you.

**Comment by mwadams** [comment]
(Other than that, I like it.)

**Comment by idg10** [comment]
Those would operate against `ITenant` and `ITenantStore`, so I think those would belong in `Corvus.Tenancy`? (The `Marain.ClientTenantProvider` already does the work of constructing the JSON Patch for you—its `ClientTenantStore` does this in its implementation of `ITenantStore.UpdateTenantAsync`.)

So unless I've missed something, there's no particular reason to limit those to `Marain.Tenancy`.

**Comment by mwadams** [comment]
I think I'm suffering from a lack of example code and an indication of what goes over the wire. If I get a tenant with some properties, set a property, change a property and update the tenant, what does the code look like, and what goes back over the wire?

**Comment by idg10** [comment]
@mwadams does https://github.com/marain-dotnet/Marain.Tenancy/pull/90/commits/e59c6e38b24d66e0ad6c9e00e4b45338f3c0a2f2 help?

**Comment by idg10** [comment]
Also,

>If I get a tenant with some properties, set a property, change a property and update the tenant

You don't. Property bag is now an immutable construct, and things using it now follow more of a command-query-separation approach. Things that need to read tenant information fetch tenants. But if you want to change something, you tell the update API what changes you want to make; this deliberately moves away from an entity-framework-like approach of enabling updates through modifications to the domain model. This goes hand in hand with the split introduced between `ITenantProvider` and `ITenantStore`. Most consumers of tenancy (which today in practice means tenanted storage providers) just want to read the properties.

**Comment by idg10** [comment]
...and also @mwadams does that ADR clarify things in the way you were looking for?

**Comment by HowardvanRooijen** [comment]
Are `ITenantProvider` and `ITenantStore` the best names now, considering the change in behaviour (assuming I understood the new command / query separation)?

**Comment by idg10** [comment]
Well `ITenantProvider` is the thing you get tenants from. `ITenantStore` is the thing that lets you edit the tenant store. So I think the names are ok. However, I'm entirely open to alternatives.

`ITenantProvider` is the name we were already using, and it also used to support editing. So arguably the name isn't ideal since that name used to encompass editing, although I'd argue it was never actually that clear that `ITenantProvider` let you modify the things. But would `ITenantSource` be more clear? `IReadOnlyTenantStore`?

**Comment by mwadams** [comment]
`ITenantProvider` literally provides tenants and nothing else. I wouldn't call it IReadOnlyTenantStore or any of those forms because it isn't a store. It is just a provider. 

ITenantSource would be fine as it is a source of tenants, but I tend to think of that as a pipeline source/sink type context which is why I discounted that originally.

Also, back in prehistory, Provider only provided and didn't update. In a moment of "where am I going to stick the update code I'll jam it on here for the time being" I broke that concept, and never fixed it...until now.

**Comment by idg10** [comment]
Superceded by #95

**Pull request closed without merging**
